spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/conference_app
    username: postgres
    password: Welcome
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc.lob.non_contextual_creation: true

server:
  error:
    include-message: always
  port: 5000
